---
#
# Tasks to create a VM based off of a CFME template
#

- name: cfme-appliance setup
  shell: |
    ./create/roles/create-cfme-appliance/scripts/create-cfme-appliance.py \
          "{{ item }}" \
          "{{ rhevm_host }}" \
          "{{ rhevm_username }}" \
          "{{ rhevm_password }}" \
          single_vm
  with_items: "{{ cfme_appliances['single'] }}"
  when: cfme_appliances.single is defined

- name: cfme-appliance setup
  shell: |
    ./create/roles/create-cfme-appliance/scripts/create-cfme-appliance.py \
          "{{ item }}" \
          "{{ rhevm_host }}" \
          "{{ rhevm_username }}" \
          "{{ rhevm_password }}" \
          multiple_vms
  with_items: "{{ cfme_appliances['multiple'] }}"
  when: cfme_appliances.multiple is defined

# - name: run configure playbook


# - name: add info to google-sheets
